### ISSUE TITLE
Send Data To Specific Runner

### ISSUE THREAD

**Issue by furesoft** [jbryan-76/dido.net#2]
Is it possible to send specific data to a runnter without saving to a file?

**Comment by jbryan-76** [comment]
Data between the application and a runner is only exchanged via the network, not via files. Runners are generic and generally "invisible" to the application. That is, the application generally doesn't "know" (nor care) whether code is running locally on the same machine or remotely on a different machine: it should work the same.

This means you as a developer do not "send" data: you simply write your code normally, then wrap a lambda expression with `DidoNet.Dido.RunAsync()` to run that expression using a remote Runner (assuming you've configured everything correctly).

**Comment by furesoft** [comment]
so you can use Stream as input/outputs?

**Comment by jbryan-76** [comment]
I'm not sure I understand your question. What are you trying to do?

You can use streams from within your code just as you normally would, as long as you understand the code running within a `RunAsync()` call is "isolated" from the main application: it does not share memory nor state nor know whether it is running on the same physical infrastructure as the main application. There is no real-time communication between the application and the code running within `RunAsync()`; It is similar to a Remote Procedure Call.

The purpose of the framework is to allow a developer to write a monolithic application while selectively executing specific code "somewhere else" simply by wrapping the invocation with `RunAsync()`. This more easily allows writing a distributed application without worrying about servers and remote APIs and security and communications protocols.
